" Plugins {{{
set nocompatible
filetype off

call plug#begin()

" navigation
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Shougo/unite.vim'
Plug 'tsukkee/unite-tag'

" general
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'mileszs/ack.vim'
Plug 'ervandew/supertab'
Plug 'junegunn/vim-easy-align', { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] }
" Plug 'Valloric/YouCompleteMe',  { 'do': './install.py --omnisharp-completer' }
Plug 'christoomey/vim-tmux-navigator'
" "Plug 'sirver/ultisnips' | Plug 'honza/vim-snippets'
Plug 'junegunn/goyo.vim'
Plug 'radenling/vim-dispatch-neovim'
Plug 'majutsushi/tagbar'
Plug 'janko-m/vim-test'
Plug 'christoomey/vim-tmux-runner'

" git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" themes
" Plug 'morhetz/gruvbox'
Plug 'joshdick/onedark.vim'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'bling/vim-airline'

" ruby
Plug 'vim-ruby/vim-ruby',    { 'for': 'ruby' }
Plug 'tpope/vim-bundler',    { 'for': 'ruby' }
Plug 'tpope/vim-rails',      { 'for': 'ruby' }

" c#
" Plug 'OrangeT/vim-csharp',      { 'for': 'cs' }
" Plug 'OmniSharp/omnisharp-vim', { 'for': 'cs', 'do': 'cd server && xbuild' }

" elixir
Plug 'elixir-lang/vim-elixir', { 'for': 'elixir' }

" coffeescript
Plug 'kchmck/vim-coffee-script',         { 'for': 'coffee' }
Plug 'mustache/vim-mustache-handlebars', { 'for': 'html.handlebars' }

" json
Plug 'elzr/vim-json', { 'for': 'json' }

" plain text
Plug 'xolox/vim-notes' | Plug 'xolox/vim-misc'

call plug#end()

filetype plugin indent on

" }}}
" Theme {{{
let &t_Co=256             " use 256 colors

" ATOM THEME
let g:onedark_termcolors=256
" set termguicolors
colorscheme onedark

" DARK THEME
" let base16colorspace=256
" set background=dark       " use dark background
" let g:gruvbox_sign_column = 'dark0'
" colorscheme gruvbox       " use gruvbox theme

" LIGHT THEME
" colorscheme Tomorrow       " use Tomorrow theme
" set background=light       " use light background
" }}}
" Change cursor shape between insert and normal mode in iTerm2.app
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
" Settings {{{
" let $NVIM_TUI_ENABLE_TRUE_COLOR=1
syntax enable
set number                    " show line numbers
" set relativenumber            " shows line numbers relative to current line
set clipboard=unnamed         " system clipboard to * register
set tabstop=2                 " tab == 2 spaces
set shiftwidth=2              " << and >> use 2 spaces
set expandtab                 " change tabs to spaces
set mouse=                    " don't use mouse in console vim
set scrolloff=5               " always show at least 3 lines at the top and bottom while scrolling
set hidden                    " Handle multiple buffers better.
set wildmenu                  " Enhanced command line completion.
set wildmode=list:longest     " Complete files like a shell.
set ignorecase                " Case-insensitive searching.
set smartcase                 " But case-sensitive if expression contains a capital letter.
set incsearch                 " Highlight matches as you type.
set hlsearch                  " Highlight matches.
set nobackup                  " Don't make a backup before overwriting a file.
set nowritebackup             " And again.
set backupdir=~/.vim/backups  " save backups here
set directory=~/.vim/swaps    " and swaps here
set backspace=2               " backspace for normal human beings
set autoread                  " If a file is changed outside of vim, automatically reload it without asking
set timeout timeoutlen=1000 ttimeoutlen=100 " fix slow O inserts
set splitbelow                " open horizontal split below current window
set splitright                " open vertical split to the right of the current window
set nowrap                    " do not wrap stuff
set lazyredraw                " redraw only when we need to.
set shortmess=aItT             " avoid 'hit enter' prompts

let mapleader = "\<space>"
" }}}
" UI {{{
set guifont=hack:h12
set guioptions-=T
set guioptions-=r
" }}}
" Whitespace {{{
" set listchars=tab:▸\ ,eol:¬,trail:·
autocmd InsertEnter * syn clear EOLWS | syn match EOLWS excludenl /\s\+\%#\@!$/
autocmd InsertLeave * syn clear EOLWS | syn match EOLWS excludenl /\s\+$/
highlight EOLWS ctermbg=red guibg=red
" }}}
" NERDTree {{{
let g:NERDTreeWinSize=40
" }}}
" Airline {{{
let g:airline#extensions#tabline#enabled = 1 " smarter tabline (shows buffers when there's only one tab open)
let g:airline_powerline_fonts = 0            " use fonts from patched powerline fonts
set laststatus=2                             " always show status bar
set showtabline=2                            " Always display the tabline, even if there is only one tab
set noshowmode                               " Hide the default mode text (e.g. -- INSERT -- below the statusline)
" }}}
" Git gutter {{{
set signcolumn=yes
highlight clear SignColumn
" }}}
" Syntastic {{{
let g:syntastic_enable_signs=1
let g:syntastic_mode_map={ 'mode': 'active',
\ 'active_filetypes': [],
\ 'passive_filetypes': ['html', 'java'] }
let g:syntastic_coffee_checkers = ['coffeelint']
let g:syntastic_check_on_open = 1
let g:syntastic_enable_signs = 1
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_style_error_symbol = "✗"
let g:syntastic_style_warning_symbol = "⚠"
" }}}
" YouCompleteMe {{{
let g:ycm_auto_trigger = 0
let g:ycm_complete_in_comments = 1
let g:ycm_complete_in_strings = 1
let g:ycm_collect_identifiers_from_comments_and_strings = 0
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:ycm_filetype_specific_completion_to_disable = {
      \ 'ruby': 1
      \}
" }}}
" Unite {{{
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
" let g:unite_source_history_yank_enable = 1
let g:unite_data_directory='~/.vim/.cache/unite'
let g:unite_enable_start_insert=1
let g:unite_prompt='» '
let g:unite_split_rule = 'botright'
let g:unite_source_rec_max_cache_files=5000
let g:unite_source_rec_async_command =
    \ ['ag', '--follow', '--nocolor', '--ignore', 'build', '--ignore', '".hg"', '--ignore', '".svn"', '--ignore', '".git"', '--ignore', '".bzr"', '--ignore', '"packages"', '--nogroup', '--hidden', '-g', '']
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
      \ '-i --vimgrep --hidden --ignore ' .
      \ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''

nnoremap <leader>pf :<C-u>Unite -auto-resize -buffer-name=file file_rec/async:!<cr>
nnoremap <leader>bb :<C-u>Unite -auto-resize -buffer-name=buffer buffer<cr>

autocmd FileType cs nnoremap <leader>f :<C-u>Unite -auto-resize -buffer-name=outline -start-insert OmniSharp/findtype<cr>
autocmd FileType cs nnoremap <leader>s :<C-u>Unite -auto-resize -buffer-name=outline -start-insert OmniSharp/findsymbols<cr>
" }}}
" Ultisnips {{{
let g:SuperTabDefaultCompletionType = '<C-n>'
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
" }}}
" OmniSharp {{{
filetype plugin on

let g:OmniSharp_server_type = 'v1'
let g:OmniSharp_host = "http://localhost:2000"

"Set the type lookup function to use the preview window instead of the status line
let g:OmniSharp_typeLookupInPreview = 0

"Timeout in seconds to wait for a response from the server
let g:OmniSharp_timeout = 1

set completeopt=longest,menuone

" Get Code Issues and syntax errors
let g:syntastic_cs_checkers = ['syntax', 'semantic', 'issues']

augroup omnisharp_commands
    autocmd!
    autocmd FileType cs nnoremap <leader>b :wa!<cr>:OmniSharpBuildAsync<cr>
    autocmd CursorHold *.cs call OmniSharp#TypeLookupWithoutDocumentation()

    autocmd FileType cs nnoremap gd :OmniSharpGotoDefinition<cr>
    autocmd FileType cs nnoremap <leader>fi :OmniSharpFindImplementations<cr>
    autocmd FileType cs nnoremap <leader>ft :OmniSharpFindType<cr>
    autocmd FileType cs nnoremap <leader>fs :OmniSharpFindSymbol<cr>
    autocmd FileType cs nnoremap <leader>fu :OmniSharpFindUsages<cr>
    autocmd FileType cs nnoremap <leader>fm :OmniSharpFindMembers<cr>
    "autocmd FileType cs nnoremap <leader>x  :OmniSharpFixIssue<cr>
    autocmd FileType cs nnoremap <leader>fx :OmniSharpFixUsings<cr>
    autocmd FileType cs nnoremap <leader>tt :OmniSharpTypeLookup<cr>
    autocmd FileType cs nnoremap <leader>dc :OmniSharpDocumentation<cr>
    autocmd FileType cs nnoremap <leader>a :call VtrSendCommand('be rake tests<cr>', 1)
    autocmd FileType cs nnoremap <leader>t :OmniSharpRunTestFixture<cr>
    " autocmd FileType cs nnoremap <leader>a :OmniSharpRunAllTests<cr>
    autocmd FileType cs nnoremap <leader>l :OmniSharpRunLastTests<cr>
    autocmd FileType cs nnoremap <leader>s :OmniSharpRunTests<cr>
    "autocmd FileType cs nnoremap <leader><space> :OmniSharpGetCodeActions<cr>
    autocmd FileType cs nnoremap <leader>nm :OmniSharpRename<cr>
    autocmd FileType cs nnoremap <leader>tp :OmniSharpAddToProject<cr>
    autocmd FileType cs nnoremap <leader>ss :OmniSharpStartServer<cr>
    autocmd FileType cs nnoremap <leader>sp :OmniSharpStopServer<cr>

    autocmd FileType cs setlocal shiftwidth=4 softtabstop=4 tabstop=4 expandtab
    autocmd FileType cs let &colorcolumn="120"
augroup END

set updatetime=500 " ms
" }}}
" Easy align {{{
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
" }}}
" Tagbar {{{
nmap <c-t> :TagbarToggle<CR>
" }}}
" Ack {{{
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif
" }}}
" Notes {{{
let g:notes_directories = ['~/Documents/Notes', '~/Dropbox/Notes']
" }}}
" vim-test {{{
let g:test#strategy="vtr"
nmap <silent> <Leader>t :TestFile<CR>
nmap <silent> <Leader>l :TestLast<CR>
nmap <silent> <Leader>s :TestNearest<CR>
nmap <silent> <Leader>a :TestSuite<CR>
" }}}
" Functions {{{
function! Preserve(command)
  " Preparation: save last search, and cursor position.
  let _s=@/
  let l = line(".")
  let c = col(".")
  " Do the business:
  execute a:command
  " Clean up: restore previous search history, and cursor position
  let @/=_s
  call cursor(l, c)
endfunction
" }}}
" Keyboard {{{

" turn off search highlight
nnoremap <leader>h :noh<CR>

" fix inconsistencies
nnoremap Y y$

" Move around splits with <c-hjkl>
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" windows
nmap <leader>ws :split<cr>
nmap <leader>wv :vsplit<cr>
nmap <leader>wc :hide<cr>

" Fix whitespace
nmap _$ :call Preserve("%s/\\s\\+$//e")<CR>

" Format file
nmap _= :call Preserve("normal gg=G")<CR>

" Toggle NERDTree
map <leader>t :NERDTreeToggle<CR>

" edit current vimrc
map <leader>hc :e ~/.vimrc<CR>
" reload vimrc
" map <leader>/ :so $MYVIMRC<CR>

" delete current file
nnoremap <leader>fr :call delete(expand('%')) \| bdelete!<CR>

" save as root
cmap w!! w !sudo tee > /dev/null %

" close current buffer
nnoremap <leader>bd :bd<cr>

" reformat json
autocmd FileType json nnoremap <leader>= :%!python -m json.tool<CR>

" rebalance windows on terminal resize
autocmd VimResized * :wincmd =

" zoom current window
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
" rebalance windows
nnoremap <leader>= :wincmd =<cr>

" Find word under cursor
nnoremap <leader>* :Ack <c-r><c-w><CR>

" Goyo toggle
nnoremap <Leader>! :Goyo<CR>
"
" }}}

" vim:foldmethod=marker:foldlevel=0
